### PR TITLE
Allow Port to be configured to other than 80

### PR DESCRIPTION
**Pull request by elgalu**
This one should be merged after https://github.com/DiUS/pact_broker-docker/pull/16

I took @derqnaque diff and his authoring on https://github.com/DiUS/pact_broker-docker/pull/11 in a first commit on this PR then added what was necessary to have it running in Travis.

### CODE REVIEW

**Comment by elgalu** [comment]
So indeed we can see the configuration Matrix now with port variants, e.g.
https://travis-ci.org/elgalu/pact_broker-docker/builds/85216431

For port 80
https://travis-ci.org/elgalu/pact_broker-docker/jobs/85216433#L247

For port 9999
https://travis-ci.org/elgalu/pact_broker-docker/jobs/85216434#L247

**Comment by bethesque** [comment]
Wow, I've never seen such nicely commented bash scripts! One problem - mac doesn't have `timeout`. Will have a poke around and see if I can find an alternative.

**Comment by elgalu** [comment]
Thanks! I like commenting particularly more on languages that are not my favorite, like bash :P but is also true that [good code is like a good joke; it needs no explanation](https://twitter.com/elgalu/status/181423062363811840) :)

I merged master to check it still works, the diff should be simpler now for this custom port feature.

**Comment by psalchow** [comment]
Is there any chance to get this PR merged?

**Comment by uglyog** [comment]
This issue has been fixed, and the latest image on docker hub should work.

**Comment by mefellows** [comment]
So should we close this?

**Comment by uglyog** [comment]
I've been able to run it with external ports other than 80, the internal container port is still 80.

**Comment by mefellows** [comment]
Thanks for the PR @elgalu, but will be closing as it is already fixed.

**Pull request closed without merging**
