### PR TITLE
Fixing sequel disconnect errors due to phusion passenger smart spawning

### PR DESCRIPTION
**Pull request by neilcampbell**
I ran into some issues with the postgresql connection resulting in the error "Sequel::DatabaseDisconnectError: PG::ConnectionBad: PQconsumeInput()". After a bit of google searching it looks as if it is related to Phusion Passenger's smart spawing method (enabled by default).

More Info:
https://groups.google.com/forum/#!topic/sequel-talk/kh-MX2IoZwg
https://www.phusionpassenger.com/library/indepth/ruby/spawn_methods/#smart-spawning-hooks

### CODE REVIEW

**Comment by bethesque** [comment]
I remember we had this problem at REA, and I think we fixed it by doing this in the Passenger config.

```
PassengerSpawnMethod conservative
```

**Comment by neilcampbell** [comment]
@bethesque Yeah that is the other way of fixing it. I tried both and they functionally have the same outcome. I was torn between the two solution, and it felt like the spawn hook was the more correct one. Thoughts?

**Comment by bethesque** [comment]
I like the one with less code personally!

**Comment by neilcampbell** [comment]
It will apparently be slower in conservative mode. Not that it is a problem.

For a little more context, I also did some reading and apparently passenger automatically sorts this out (with the same hook) when using active record, so this fix just bring it in-line with what would be happening to an active record connection, which I liked.

Happy either way to be honest :)
Let me know and I can change to conservative mode and update the PR.

**Comment by bethesque** [comment]
Let's go with what you've done and tested then, if they do the same thing.

**Comment by neilcampbell** [comment]
@bethesque Awesome stuff. Thanks for merging this so quickly! Can you please also publish a new version to the docker hub?

**Comment by bethesque** [comment]
Do you have a dockerhub account? I'll add you to the collaborators.

**Comment by neilcampbell** [comment]
Thanks Beth. Username is neilcampbell.

**Comment by bethesque** [comment]
Sorry, have to get our admin guy to do it, I don't have the permissions. New laptop, so I didn't have docker installed. Trying to do it in the background today!

**Comment by neilcampbell** [comment]
@bethesque I got an email saying that I have been given collaborator access, however I am still unable to push to the docker hub and I get "unauthorized: access to the requested resource is not authorized". To ensure it wasn't a login issue, I pushed the same docker container to my own account and that worked.

**Comment by k-ong** [comment]
@neilcampbell, give me a minute. I'll see if I can fix it up. Must have missed something.

**Comment by k-ong** [comment]
can you try it now? thanks!

**Comment by neilcampbell** [comment]
@k-ong Works perfect now. Thanks for sorting that one!

**Pull request merged**
