### PR TITLE
fix: Dockerfile command syntax

### PR DESCRIPTION
**Pull request by k-ong**

### CODE REVIEW

**Comment by bethesque** [comment]
How did that even work before?

**Comment by k-ong** [comment]
`&` is background in linux. So there're no errors thrown and the command runs in the background

**Comment by TimothyJones** [comment]
Wouldn't running all those in parallel fail sometimes, though?

**Comment by bethesque** [comment]
Probably, yes. Obviously, we hadn't hit a failure yet. Good catch Ken.

**Pull request merged**
