### PR TITLE
Add TravisCI automated tests

### PR DESCRIPTION
**Pull request by elgalu**
After this PR we can start enjoying Travis builds :)
You will also need to enable the project in Travis, on your organization account:
https://travis-ci.org/profile/DiUS

### CODE REVIEW

**Comment by bethesque** [comment]
Love your work, thanks!

**Comment by bethesque** [comment]
@elgalu got a failure, reckon it needs a longer wait, or is there a problem with the command itself? https://travis-ci.org/DiUS/pact_broker-docker/builds/85007392

**Comment by elgalu** [comment]
Yes I see it, there is a timing issue, I'll fix it in another PR with an active wait mechanism (no sleeps)

**Comment by elgalu** [comment]
History continues in PR #16

**Pull request merged**
