### PR TITLE
Pactbroker

### PR DESCRIPTION
**Pull request by itsmenandess**
PactBroker with Global variable to configure DataSource(DATA_ADAPTER)

### CODE REVIEW

**Comment by bethesque** [comment]
Looks good. Just one tweak - it's best practice to allow patch versions for bug fixes in the version restriction, so "~>0.3" is preferred over "0.3.16".

**Comment by itsmenandess** [comment]
Hi Mam,

Thanks, I will update the same.

Regards,
Nandesskumar V

**Comment by bethesque** [comment]
Ping me when it's done, because there are no notifications when there are new pushes made to an existing PR.

**Comment by bethesque** [comment]
I got bored with waiting and did it myself!

**Pull request merged**
